language: node_js
cache: yarn
node_js:
- node
script: skip
deploy:
  provider: npm
  email: npm@netflix.com
  on:
    tags: true
  api_key:
    secure: deeB8wodqQTUpoePi8v8/vhv6p1K58HvCnWwPMttWKIfCSKp3tbPRGfWeI13Ah6Fzt4QLJSJnnfqRghlBaBnsVjtKOAhuH0nK0FKRvOVp3hPiRYAX2zSw3oYg8jGbBrR24fHaavQ85D93PaWgkIaohnhmWn+ZbM8ihprcSgd9jysKUuE4BaMI58AGt4KXQCLerTeqsaS6RXBnhumZUkZwVi7L9G4ym8BxmE1ZnhbMhER/OIIxSDktElgc2Dajfxl++EhcWTGWbqFpuYwjVJsBcurzmbjmZ1ahBW4GkLNWCe84ouP9as/ehKZVyNOviszUYQonzq0czdL94gFkeiqIGngFHoH1Z3iPv12p0E7akeYN2zid+nUkj5Zl/pj51B5GUez8pZGetQngFVM/Y3gCQ2tz+ZEyttIlxJkSl7h8ZkKE+aMKhLK/zP0C6X8dfrbZJymLMlHhGfY5bZB5mcekNOoNoycNW8MbKQapVbWmHnbPTzyPTazyUVnNpmkA0XkQ/5YCh2uo8IiIa0waYz0V65dI4jp2B0wejnjrhR+MtXmVWs83xOeFa4J9ryPRvmfCjUxsnFEnNa3zRLIKIUV6Qi+5jcbjKUHW2g7SaVH5OPZlOyJ7M3EiAUu4D4guamA72BsCMPhSZlPuVxdT8QJJUqbN9iNqobg/wr0D7GUjGY=
