language: node_js
cache: yarn
node_js:
- node
script: skip
deploy:
  provider: npm
  email: npm@netflix.com
  on:
    tags: true
  api_key:
    secure: jY960X5UUd6ID9MK27YGEkivLk1mJXT5I1L93xqY+owlD9sdcVZX1VlTB1u4ystItH73vuNdw0OVbpAAuqjvEOg675OfYg+zLbDvGNHN5kKmPpoU7zFfYtga4qnJE/pxQVHfyk1ve9kx5qJX8XLL+tqbws3YVXhKDBL18zyYdzlxFiJFlI2cntDAqVhe9+RKyzr2ahu/pJV64kAplyIASBLtUx2pUBiH0kqSnf5H0VDrAgCWroC+j7SHahVKN47iusQ4ogLIj3S2TlWdXl2OCSn4/f6RCCtOo6J+jSo6MKTTHPSJpn/MgjscEzgxt7XKzj+08NCl4So4R1qUzHHplDVOgvOL2YrJkbZvDSEsH0eyjIjnDn/6ClNMqoRCSkHKgieo8WM/hqpWhLTBQYMqkhuYEN1zHLhb8rHFHoQesmMj8azt1btm+amGZB4YQwgneWbuHf5theibRofINxFolVP5zzIl+bogWfST0y1sHARis/ERhpXUfo/NF2lOEs9WnwumHX3WURXl49pKm2H2kdn7TGzNvNK60lL/qt/efK7x2CmhsY8NUn1BHoIhQZDltUbBn7xa7yUVHi/YUhw9vIKDZeWBA/VYilCyLch0TYLvnlkN0g5iyH53SKsXvSPhClYW7KKU2ql3bdbmlNzfdufjX2IugtWY3t2FKUJOS2U=
